In [1]:
import numpy as np
import factor
import utils

In [2]:
pos_path = 'data/train_pos.npy'
neg_path = 'data/train_neg.npy'
kg_path = 'data/kg.txt'

In [3]:
train_pos,train_neg = utils.load_train_data( pos_path, neg_path)
kg_lines = utils.load_kg_data( kg_path )

In [4]:
train_pos.shape, train_neg.shape, len(kg_lines)

((26638, 3), (24037, 3), 20195)

In [5]:
# (head, tail, relation)
train_pos[:5], train_neg[:5]

(array([[   0, 1113,    1],
        [   0,  736,    1],
        [   0,  888,    1],
        [   0,  636,    1],
        [   1,  374,    1]]),
 array([[   0,   87,    0],
        [   0, 1791,    0],
        [   0,  587,    0],
        [   0,  100,    0],
        [   1,  680,    0]]))

In [6]:
# (item, relation, item), separated by '\t'
kg_lines[:5]

['749\tfilm.film.writer\t2347\n',
 '1410\tfilm.film.language\t2348\n',
 '1037\tfilm.film.language\t2348\n',
 '1088\tfilm.film.writer\t2349\n',
 '1391\tfilm.film.language\t2348\n']

In [7]:
record = kg_lines[1].strip().split('\t')
record

['1410', 'film.film.language', '2348']

In [8]:
len(kg_lines)

20195

In [22]:
config = {'num_factors':30,'learning_rate':0.03,'regularization':0.03,'epochs':25}

In [23]:
recommender = factor.KGRS(config, train_pos, train_neg,kg_lines=kg_lines)

独热编码结果：
[[0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]]


/Users/cooperz/opt/anaconda3/envs/ai_proj2/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [24]:
np.max(train_pos[:, 1])

2346

In [25]:
recommender.kg_relation_dict

{'film.film.rating': array([0., 0., 0., 0., 1., 0., 0.]),
 'film.film.country': array([1., 0., 0., 0., 0., 0., 0.]),
 'film.film.director': array([0., 1., 0., 0., 0., 0., 0.]),
 'film.film.star': array([0., 0., 0., 0., 0., 1., 0.]),
 'film.film.writer': array([0., 0., 0., 0., 0., 0., 1.]),
 'film.film.language': array([0., 0., 0., 1., 0., 0., 0.]),
 'film.film.genre': array([0., 0., 1., 0., 0., 0., 0.])}

In [26]:
recommender.training()

In [27]:
# (head, tail, relation)
train_pos[:5], train_neg[:5]

(array([[5167,  698,    1],
        [5751, 1053,    1],
        [5984, 2058,    1],
        [2213,  887,    1],
        [3516,  873,    1]]),
 array([[1958, 2290,    0],
        [4631, 2246,    0],
        [2782,  209,    0],
        [5995,  979,    0],
        [ 747,  354,    0]]))

In [28]:
recommender.predict_score(3517, 2319), recommender.predict_score(4155,1140)

(0.06777454750717775, 0.7413931692698498)

In [29]:
test_data = np.array([[3517, 2319], [ 697, 2224],[4155, 1140],[5931, 1064]])
recommender.eval_ctr(test_data)

array([0.06777455, 0.19323612, 0.74139317, 0.88834998])

In [30]:
user_4155 = train_pos[train_pos[:,0]==4155]
user_5931 = train_pos[train_pos[:,0]==5931]
user_4155, user_5931

(array([[4155, 1140,    1],
        [4155,  371,    1],
        [4155, 1139,    1],
        [4155, 1528,    1]]),
 array([[5931, 1374,    1],
        [5931, 1298,    1],
        [5931, 1865,    1],
        [5931, 1064,    1],
        [5931, 1792,    1],
        [5931, 1924,    1],
        [5931,  789,    1],
        [5931, 1770,    1],
        [5931,  699,    1],
        [5931, 1319,    1],
        [5931,  911,    1],
        [5931,  198,    1],
        [5931, 1627,    1],
        [5931, 1166,    1],
        [5931,  207,    1],
        [5931, 1229,    1],
        [5931,   89,    1],
        [5931, 1687,    1],
        [5931,   67,    1]]))

In [31]:
user_list = [4155,5931]
recommender.eval_topk(user_list) # topk=5

[[750, 476, 1139, 371, 879], [348, 1404, 632, 1900, 736]]